# Generated by Django 3.1.7 on 2021-05-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210513_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
