# Generated by Django 3.1.7 on 2021-05-14 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210514_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='user',
            name='member_since',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
