# Generated by Django 3.1.7 on 2021-05-15 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210514_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='fav_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='fav_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
