# Generated by Django 3.1.7 on 2021-05-16 09:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210515_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', null=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(unique=True, upload_to='')),
                ('date', models.DateField(default=datetime.date.today)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
                ('fans', models.ManyToManyField(blank=True, related_name='fav_tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
