# Generated by Django 3.1.7 on 2021-05-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20210516_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='kinds',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='music.Kind'),
        ),
    ]
