# Generated by Django 3.1.7 on 2021-05-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210516_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='title',
            field=models.CharField(default='Unknown', max_length=100, unique=True),
        ),
    ]
