# Generated by Django 3.1.7 on 2021-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20210516_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='kinds',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='music.Kind'),
        ),
    ]
